---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Python and pip
      apt:
        name: [python3, python3-pip]
        state: present
    - name: Install Flask
      pip:
        name: Flask
        state: present